import { z } from "zod";
import { IsoDateTimeSchema, SemVerSchema, StableIdSchema } from "./index";

/**
 * Codex Manifest: deterministic index of all discovered codex files
 * Generated by CodexRegistry.load(), used for rapid lookups + audit
 */

export const CodexManifestEntrySchema = z
    .object({
        id: StableIdSchema,
        schema_version: SemVerSchema,
        name: z.string().min(1),
        sha256: z.string().regex(/^[a-f0-9]{64}$/i, "Expected sha256 hex (64 chars)"),
        source_path: z.string().min(1),
        updated_at_utc: IsoDateTimeSchema,
    })
    .strict();

export const CodexManifestSchema = z
    .object({
        manifest_version: SemVerSchema,
        generated_at_utc: IsoDateTimeSchema,
        root_dir: z.string().min(1),
        count: z.number().int().min(0),
        entries: z.array(CodexManifestEntrySchema),
    })
    .strict();

export type CodexManifest = z.infer<typeof CodexManifestSchema>;
export type CodexManifestEntry = z.infer<typeof CodexManifestEntrySchema>;
