import type { AvatarDNA } from "./avatarDNA.js";

export const AVATAR_DNA_PRESETS: AvatarDNA[] = [
  {
    morphs: {
      height: 0.08,
      shoulderWidth: 0.14,
      bodyFat: -0.18,
      muscle: 0.22,
      headSize: 0.02,
      jawWidth: 0.18,
      jawForward: 0.06,
      cheekboneHeight: 0.16,
      cheekboneWidth: 0.06,
      chinLength: 0.04,
      noseWidth: -0.06,
      noseBridgeHeight: 0.12,
      noseTipUp: 0.02,
      eyeSize: 0.1,
      eyeSpacing: 0.04,
      browHeight: 0.06,
      browThickness: 0.1,
      lipFullness: 0.02,
      earSize: -0.02,
      neckThickness: 0.06,
    },
    materials: {
      skinColor: "#d6b08f",
      hairColor: "#1d1712",
      roughness: 0.82,
      metalness: 0.0,
    },
    textures: {
      skinMap: "/textures/skin/skin_01.jpg",
      clothingMap: "/textures/clothes/outfit_01.jpg",
    },
    postfx: { bloom: 0.22, ao: 0.42, smaa: true },
    quality: { shadows: true, shadowMapSize: 2048 },
  },
  {
    morphs: {
      height: -0.04,
      shoulderWidth: -0.06,
      bodyFat: 0.1,
      muscle: -0.06,
      headSize: 0.04,
      jawWidth: -0.1,
      jawForward: -0.02,
      cheekboneHeight: 0.06,
      cheekboneWidth: -0.02,
      chinLength: -0.04,
      noseWidth: -0.12,
      noseBridgeHeight: 0.18,
      noseTipUp: 0.1,
      eyeSize: 0.18,
      eyeSpacing: -0.02,
      browHeight: 0.12,
      browThickness: -0.08,
      lipFullness: 0.14,
      earSize: 0.06,
      neckThickness: -0.04,
    },
    materials: {
      skinColor: "#f2d6c6",
      hairColor: "#c7a06a",
      roughness: 0.75,
      metalness: 0.0,
    },
    textures: {
      skinMap: "/textures/skin/skin_02.jpg",
      clothingMap: "/textures/clothes/outfit_02.jpg",
      maskMap: "/textures/masks/makeup_01.png",
    },
    postfx: { bloom: 0.28, ao: 0.48, smaa: true },
    quality: { shadows: true, shadowMapSize: 2048 },
  },
  {
    morphs: {
      height: 0.02,
      shoulderWidth: 0.06,
      bodyFat: -0.1,
      muscle: 0.1,
      headSize: -0.02,
      jawWidth: 0.06,
      jawForward: 0.14,
      cheekboneHeight: 0.02,
      cheekboneWidth: 0.1,
      chinLength: 0.1,
      noseWidth: 0.08,
      noseBridgeHeight: -0.04,
      noseTipUp: -0.06,
      eyeSize: -0.04,
      eyeSpacing: 0.06,
      browHeight: -0.08,
      browThickness: 0.18,
      lipFullness: -0.06,
      earSize: -0.04,
      neckThickness: 0.1,
    },
    materials: {
      skinColor: "#7d5a44",
      hairColor: "#0e0d0f",
      roughness: 0.86,
      metalness: 0.02,
    },
    textures: {
      skinMap: "/textures/skin/skin_03.jpg",
      clothingMap: "/textures/clothes/outfit_03.jpg",
    },
    postfx: { bloom: 0.14, ao: 0.55, smaa: false },
    quality: { shadows: true, shadowMapSize: 1024 },
  },
  {
    morphs: {
      height: 0.14,
      shoulderWidth: 0.2,
      bodyFat: -0.24,
      muscle: 0.34,
      headSize: -0.04,
      jawWidth: 0.24,
      jawForward: 0.1,
      cheekboneHeight: 0.1,
      cheekboneWidth: 0.12,
      chinLength: 0.06,
      noseWidth: 0.0,
      noseBridgeHeight: 0.06,
      noseTipUp: -0.02,
      eyeSize: 0.02,
      eyeSpacing: 0.02,
      browHeight: 0.02,
      browThickness: 0.08,
      lipFullness: -0.02,
      earSize: 0.02,
      neckThickness: 0.16,
    },
    materials: {
      skinColor: "#c28d63",
      hairColor: "#2a2e3a",
      roughness: 0.78,
      metalness: 0.0,
    },
    textures: {
      skinMap: "/textures/skin/skin_04.jpg",
      clothingMap: "/textures/clothes/outfit_04.jpg",
      maskMap: "/textures/masks/scar_01.png",
    },
    postfx: { bloom: 0.18, ao: 0.46, smaa: true },
    quality: { shadows: true, shadowMapSize: 2048 },
  },
  {
    morphs: {
      height: -0.1,
      shoulderWidth: 0.02,
      bodyFat: 0.06,
      muscle: -0.02,
      headSize: 0.1,
      jawWidth: -0.16,
      jawForward: -0.1,
      cheekboneHeight: 0.2,
      cheekboneWidth: -0.06,
      chinLength: -0.1,
      noseWidth: -0.1,
      noseBridgeHeight: 0.1,
      noseTipUp: 0.08,
      eyeSize: 0.26,
      eyeSpacing: -0.06,
      browHeight: 0.18,
      browThickness: -0.14,
      lipFullness: 0.22,
      earSize: 0.1,
      neckThickness: -0.08,
    },
    materials: {
      skinColor: "#ffe0d3",
      hairColor: "#ff4ea3",
      roughness: 0.72,
      metalness: 0.0,
    },
    textures: {
      skinMap: "/textures/skin/skin_05.jpg",
      clothingMap: "/textures/clothes/outfit_05.jpg",
      maskMap: "/textures/masks/tattoo_01.png",
    },
    postfx: { bloom: 0.36, ao: 0.4, smaa: true },
    quality: { shadows: false, shadowMapSize: 1024 },
  },
  {
    morphs: {
      height: 0.0,
      shoulderWidth: -0.02,
      bodyFat: -0.04,
      muscle: 0.02,
      headSize: 0.0,
      jawWidth: -0.02,
      jawForward: 0.0,
      cheekboneHeight: 0.0,
      cheekboneWidth: 0.0,
      chinLength: 0.0,
      noseWidth: 0.0,
      noseBridgeHeight: 0.0,
      noseTipUp: 0.0,
      eyeSize: 0.0,
      eyeSpacing: 0.0,
      browHeight: 0.0,
      browThickness: 0.0,
      lipFullness: 0.0,
      earSize: 0.0,
      neckThickness: 0.0,
    },
    materials: {
      skinColor: "#d8b59a",
      hairColor: "#2b1d14",
      roughness: 0.85,
      metalness: 0.0,
    },
    textures: {
      skinMap: "/textures/skin/skin_neutral.jpg",
      clothingMap: "/textures/clothes/outfit_neutral.jpg",
      maskMap: "/textures/masks/mask_none.png",
    },
    postfx: { bloom: 0.2, ao: 0.45, smaa: true },
    quality: { shadows: true, shadowMapSize: 1024 },
  },
  {
    morphs: {
      height: 0.06,
      shoulderWidth: 0.1,
      bodyFat: -0.08,
      muscle: 0.06,
      headSize: -0.06,
      jawWidth: -0.04,
      jawForward: 0.02,
      cheekboneHeight: -0.06,
      cheekboneWidth: 0.02,
      chinLength: 0.02,
      noseWidth: 0.14,
      noseBridgeHeight: -0.1,
      noseTipUp: -0.12,
      eyeSize: -0.1,
      eyeSpacing: 0.1,
      browHeight: -0.14,
      browThickness: 0.06,
      lipFullness: -0.1,
      earSize: -0.06,
      neckThickness: 0.04,
    },
    materials: {
      skinColor: "#9b7a5b",
      hairColor: "#ffffff",
      roughness: 0.6,
      metalness: 0.08,
    },
    textures: {
      skinMap: "/textures/skin/skin_06.jpg",
      clothingMap: "/textures/clothes/outfit_06.jpg",
    },
    postfx: { bloom: 0.12, ao: 0.62, smaa: false },
    quality: { shadows: true, shadowMapSize: 2048 },
  },
  {
    morphs: {
      height: 0.04,
      shoulderWidth: 0.04,
      bodyFat: -0.14,
      muscle: 0.14,
      headSize: 0.02,
      jawWidth: 0.04,
      jawForward: -0.02,
      cheekboneHeight: 0.08,
      cheekboneWidth: 0.1,
      chinLength: -0.02,
      noseWidth: -0.02,
      noseBridgeHeight: 0.04,
      noseTipUp: 0.0,
      eyeSize: 0.06,
      eyeSpacing: 0.0,
      browHeight: 0.04,
      browThickness: 0.04,
      lipFullness: 0.06,
      earSize: -0.02,
      neckThickness: 0.08,
    },
    materials: {
      skinColor: "#b08a74",
      hairColor: "#3a6ff2",
      roughness: 0.7,
      metalness: 0.0,
    },
    textures: {
      skinMap: "/textures/skin/skin_07.jpg",
      clothingMap: "/textures/clothes/outfit_07.jpg",
      maskMap: "/textures/masks/warpaint_01.png",
    },
    postfx: { bloom: 0.3, ao: 0.44, smaa: true },
    quality: { shadows: true, shadowMapSize: 1024 },
  },
];

export type NamedAvatarDNAPreset = {
  id: string;
  name: string;
  dna: AvatarDNA;
};

const PRESET_NAMES: Array<Pick<NamedAvatarDNAPreset, "id" | "name">> = [
  { id: "ranger", name: "Ranger" },
  { id: "radiant", name: "Radiant" },
  { id: "obsidian", name: "Obsidian" },
  { id: "scarred", name: "Scarred" },
  { id: "neon", name: "Neon" },
  { id: "neutral", name: "Neutral" },
  { id: "silverfox", name: "Silverfox" },
  { id: "warpaint", name: "Warpaint" },
];

export const AVATAR_DNA_NAMED_PRESETS: NamedAvatarDNAPreset[] = AVATAR_DNA_PRESETS.map((dna, index) => ({
  id: PRESET_NAMES[index]?.id ?? `preset_${String(index + 1).padStart(2, "0")}`,
  name: PRESET_NAMES[index]?.name ?? `Preset ${index + 1}`,
  dna: { ...dna },
}));

export const AVATAR_DNA_PRESET_JOBS: Array<{ avatar_id: string; dna: AvatarDNA }> = AVATAR_DNA_NAMED_PRESETS.map(
  (preset) => ({
    avatar_id: preset.id,
    dna: { ...preset.dna },
  }),
);
