export const ROUTES = {
  root: "/",
  hub: "/hub",
  labRoot: "/lab",
  settings: "/settings",
  apps: {
    root: "/apps",
    byId: (id: string) => `/apps/${id}`,
  },
  lab: {
    studio: "/lab/studio",
    launcherControl: "/lab/launcher-control",
    nucleus: "/lab/nucleus",
    brain: "/lab/brain",
    avatarCompiler: "/lab/avatar-compiler",
    heartTimeline: "/lab/heart-timeline",
    lexicon: "/lab/lexicon",
    leximorph: "/lab/leximorph",
    chat: "/lab/chat",
    gameEngine: "/lab/game-engine",
    gameStudio: "/lab/game-studio",
    prefabEngine: "/lab/prefab-engine",
    graphics: "/lab/graphics",
    worldGraph: "/lab/world-graph",
    nexus: "/lab/nexus",
    flowstate: "/lab/flowstate",
    evidence: "/lab/evidence",
    dashboard: "/lab/dashboard",
    ecosystem: "/lab/ecosystem",
    pipelineResults: "/lab/pipeline-results",
    terrainErosion: "/lab/terrain-erosion",
    wfc: "/lab/wave-function-collapse",
    ecsArchitecture: "/lab/ecs-architecture",
    memoryAllocators: "/lab/memory-allocators",
    worldEngineBlueprint: "/lab/world-engine-blueprint",
    mathEngine: "/lab/math-engine",
    mathWorkspace: "/lab/math-workspace",
    mathDependencyGraph: "/lab/math-dependency-graph",
    complexPlayground: "/lab/complex-playground",
    matrixPlayground: "/lab/matrix-playground",
    svgRendering: "/lab/svg-rendering",
    math3D: "/lab/3d-mathematics",
    physics: "/lab/physics",
    vectorPhysics: "/lab/vector-physics",
    iconGenerator: "/lab/icon-generator",
    agentChat: "/lab/agent-chat",
    graphicsGenerator: "/lab/graphics-generator",
    avatarEditor: "/lab/avatar-editor",
  },
} as const;
